---
title: "simpsons-guests"
author: "Orla"
date: "8/3/2022"
output: html_document
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
theme_set(theme_light())

simpsons <- simpsons <- readr::read_delim("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-08-27/simpsons-guests.csv", delim = "|", quote = "") %>%
  # add self onto the original dataset
  mutate(self = str_detect(role, "sel|selves"))

```

## Which guest has appeared the most as themselves?

```{r, echo=FALSE}

# what gues stars appeared the most, what role do they play
simpsons %>%
  count(guest_star, role, sort = TRUE) %>%
  # who played himself and herself the most?
  filter(role %in% c("Himself", "Herself"))


simpsons %>%
  count(guest_star, role, sort = TRUE) %>%
  # who played himself, herself or themselves (group) the most?
  filter(str_detect(role, "sel|selves")) %>%
  count(role, sort = TRUE) %>%
  View()


simpsons %>%
  filter(self) %>%
  count(guest_star, sort = TRUE) %>%
  filter(n > 1) %>%
  mutate(guest_star = fct_reorder(guest_star, n)) %>%
  ggplot(aes(guest_star, n)) +
  geom_col() +
  coord_flip() +
  labs(title = "Who has played themselves in multiple Simpsons episodes?")

```




```{r, echo=FALSE}
# filters where a guest star appears as multiple characters
simpsons %>%
  filter(str_detect(role, ";")) %>%
  add_count(role)

# separates new rows where a guest role appears in the season
simpsons %>%
  # separated by semi colon and spaces
  separate_rows(role, sep = ";\\s+ ") %>%
  #count(role, sort = TRUE)
  add_count(role, sort = TRUE) %>%
  filter(n >= 10) %>%
  count(season = parse_number(season), role) %>%
  mutate(role = fct_reorder(role, -n, sum)) %>%
  ggplot(aes(season, n)) +
  geom_col() +
  facet_wrap(~ role)

```
```{r}

simpsons

```
